function [ matrix_of_FingerPrint_DataBank_for_all_Devices, number_of_Bursts_for_all_of_Devices ] = DataBank_Structure_to_DataBank_Matrix_Converter (    vertical_Structure_of_FingerPrints_DataBank_for_all_Devices, ...
                                                                                                                                                        selected_Type_of_FingerPrints_for_postProcessing,            ...
                                                                                                                                                        selected_Indices_of_Devices,                                 ...
                                                                                                                                                        selected_DataSet_Name,                                       ...
                                                                                                                                                        general_PlotTitle,                                           ...
                                                                                                                                                                                                                     ...
                                                                                                                                                        do_You_Want_to_Draw_FPPlot_for_Initial_Data,                 ...                                                             
                                                                                                                                                        selected_Function_for_Converting_the_MatriceRows_in_FingerPrintGraph_String, ...
                                                                                                                                                        selected_Function_for_Converting_the_MatriceCols_in_FingerPrintGraph_String, ...                                                           
                                                                                                                                                        number_of_Saved_Bursts_for_a_Single_Device_for_FFPlot,       ...
                                                                                                                                                        number_of_Added_Zeros_Between_Devices,                       ...
                                                                                                                                                        application_or_Training                                      ...
                                                                                                                                                        ) 
                                                                                                                                                    
    % Extracing all the devices from the DataBank (for both cases of "Training" and "Application")
        FingerPrints_DataBank_for_all_Devices =[];
        dataBank_class_Label_for_all_Devices = [];
        for device_Index = 1 : size ( vertical_Structure_of_FingerPrints_DataBank_for_all_Devices, 1 )
            temp = [ vertical_Structure_of_FingerPrints_DataBank_for_all_Devices( device_Index, 1 ).(selected_Type_of_FingerPrints_for_postProcessing) ];
            number_of_Bursts_for_all_of_Devices ( 1, device_Index ) = size (temp, 2 );
            FingerPrints_DataBank_for_all_Devices = [ FingerPrints_DataBank_for_all_Devices temp ];

            dataBank_class_Label_for_all_Devices  = [ dataBank_class_Label_for_all_Devices ones( 1, size ( temp, 2 ))*device_Index ];        

        end
        matrix_of_FingerPrint_DataBank_for_all_Devices = [ FingerPrints_DataBank_for_all_Devices; dataBank_class_Label_for_all_Devices ];

    % Reducing the Number of Devices
        class_Labels = matrix_of_FingerPrint_DataBank_for_all_Devices ( end, : );
        selected_Indices_of_Devices = selected_Indices_of_Devices (:)';
        temp_matrix_of_FingerPrint_DataBank_for_all_Devices = [];
        for device_Index = 1 : length ( selected_Indices_of_Devices )
            temp_Indices = ( class_Labels == selected_Indices_of_Devices ( 1, device_Index ));
            temp         = matrix_of_FingerPrint_DataBank_for_all_Devices ( :, temp_Indices );
            temp_matrix_of_FingerPrint_DataBank_for_all_Devices = [ temp_matrix_of_FingerPrint_DataBank_for_all_Devices, temp];
            
        end
        matrix_of_FingerPrint_DataBank_for_all_Devices = temp_matrix_of_FingerPrint_DataBank_for_all_Devices;
        
        number_of_Bursts_for_all_of_Devices = number_of_Bursts_for_all_of_Devices(1, selected_Indices_of_Devices);

   % Making the Matrix for 'FingerPrint Plot' 
        if ( do_You_Want_to_Draw_FPPlot_for_Initial_Data == 1 )
            Matrix_for_InitialDataBank_FingerPrintPlot_Producer_Manager (  matrix_of_FingerPrint_DataBank_for_all_Devices,           ...
                                                                           selected_DataSet_Name,                                     ...
                                                                                                                                      ...
                                                                           selected_Indices_of_Devices,            ...                       
                                                                           number_of_Bursts_for_all_of_Devices,                       ...
                                                                           general_PlotTitle,                                         ...
                                                                                                                                      ...
                                                                           selected_Function_for_Converting_the_MatriceRows_in_FingerPrintGraph_String, ...
                                                                           selected_Function_for_Converting_the_MatriceCols_in_FingerPrintGraph_String, ...                                                           
                                                                           number_of_Saved_Bursts_for_a_Single_Device_for_FFPlot,     ...
                                                                           number_of_Added_Zeros_Between_Devices,                     ...
                                                                           application_or_Training                                    ...
                                                                           );
                                                                       
        end
end




