function [ matrix_of_Selected_Statistics_for_Current_Device, matrix_of_FingerPrints_for_Current_Device, cell_of_Names_of_Covered_Fields_for_current_Device, information_of_Bursts_for_Current_Device  ] =  FingerPrints_for_a_Single_Device (  vertical_Cell_of_Characteristics_Names,                    ...                                          ... used here
                                                                                                                                                                                                                                               vertical_Cell_of_Statistics_Names,                                ... used here
                                                                                                                                                                                                                                                                                                                 ...
                                                                                                                                                                                                                                               strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix,        ... 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row' or 'each_Statistics_of_Characteristics_in_Seperate_Rows'                                                                                                                                    
                                                                                                                                                                                                                                               selected_Algorithm_for_Making_FingerPrint_of_a_Single_Burst,      ... 
                                                                                                                                                                                                                                               Vertical_Structure_of_all_Bursts)

% matrix_of_Selected_Statistics_for_Current_Device (Matrix)
    %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
    % Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
    % Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
    %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    %              |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                        |                                                                                                                                                                                  
    %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    %              |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                              |
    %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      


% matrix_of_FingerPrints_for_Current_Device (Matrix)
    %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
    % Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
    % Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
    %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    %              |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
    %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
    
    
    %% Section 1: Collecting Essential Parameters
        % Level 1: Converting the 'Vertical_Structure_of_all_Bursts' to 'Vertical Case'
            Vertical_Structure_of_all_Bursts = Converter_to_Horizontal_or_Vertical_Vector( Vertical_Structure_of_all_Bursts, 'Vertical', 'vertical_Structure_of_a_Single_Burst' );     
            

    %% Section 2: Calculation of 'FingerPrint for current device'
        [ matrix_of_Selected_Statistics_for_Current_Device, matrix_of_FingerPrints_for_Current_Device, cell_of_Names_of_Covered_Fields_for_current_Device, information_of_Bursts_for_Current_Device ]  = Calculation_of_Statistics_for_all_Bursts (    vertical_Cell_of_Characteristics_Names,                           ... used here
                                                                                                                                                                                                   vertical_Cell_of_Statistics_Names,                                ... used here
                                                                                                                                                                                                                                                     ...
                                                                                                                                                                                                   strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix,        ... 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row' or 'each_Statistics_of_Characteristics_in_Seperate_Rows'                                                                  
                                                                                                                                                                                                   selected_Algorithm_for_Making_FingerPrint_of_a_Single_Burst,      ... used in: Instantaneous_Element_Extractor / selected_Instantaneous_Element_Function 
                                                                                                                                                                                                   Vertical_Structure_of_all_Bursts);


end