function [ matrix_of_Selected_Statistics_for_all_Bursts, matrix_of_FingerPrints_for_all_Bursts, cell_of_Names_of_Covered_Fields_for_all_Bursts_in_Order, information_of_all_Bursts ] = Calculation_of_Statistics_for_all_Bursts ( vertical_Cell_of_Characteristics_Names,                           ... used here
                                                                                                                                                                                                                                   vertical_Cell_of_Statistics_Names,                                ... used here
                                                                                                                                                                                                                                                                                                     ...
                                                                                                                                                                                                                                   strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix,        ... 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row' or 'each_Statistics_of_Characteristics_in_Seperate_Rows'                                                                  
                                                                                                                                                                                                                                   selected_Algorithm_for_Making_FingerPrint_of_a_Single_Burst,      ... 
                                                                                                                                                                                                                                   Vertical_Structure_of_all_Bursts)   
                                                                                                                               
%% Input:
    % Vertical_Structure_of_all_Bursts (Structure)
        %  -----------------------------------------------------------------------------------------------------------------------
        %           |                 |                             |    |                               |                        |               
        %           |                 |                             | 1  | a_Single_subRegion (Field):   | I+Q (Vertical Vector)  |
        %           |                 |                             |    |                               |                        |               
        %           |                 |                             --------------------------------------------------------------
        %           |                 |                             | .  |               .               |            .           |             
        %           |       1         |   a_Single_Burst (Field):   | .  |               .               |            .           | 
        %           |                 |                             | .  |               .               |            .           |             
        %           |                 |                             --------------------------------------------------------------
        %           |                 |                             |    |                               |                        |               
        %           |                 |                             | 33 | a_Single_subRegion (Field):   | I+Q (Vertical Vector)  |
        %           |                 |                             |    |                               |                        |            
        %           ---------------------------------------------------------------------------------------------------------------
        %           |       .         |                                       .                                                   |                  
        %  Singel   |       .         |                                       .                                                   |                                
        %  Device   |       .         |                                       .                                                   |                  
        %           ---------------------------------------------------------------------------------------------------------------
        %           |                 |                             |    |                               |                        |               
        %           |                 |                             | 1  | a_Single_subRegion (Field):   | I+Q (Vertical Vector)  |
        %           |                 |                             |    |                               |                        |               
        %           |                 |                             --------------------------------------------------------------
        %           |                 |                             | .  |               .               |            .           |             
        %           |       N         |   a_Single_Burst (Field):   | .  |               .               |            .           | 
        %           | ( eg. N = 160,  |                             | .  |               .               |            .           |             
        %           | N: Number of    |                             --------------------------------------------------------------
        %           | Bursts )        |                             |    |                               |                        |               
        %           |                 |                             | 33 | a_Single_subRegion (Field):   | I+Q (Vertical Vector)  |
        %           |                 |                             |    |                               |                        |            
        %  ------------------------------------------------------------------------------------------------------------------------                    
        
        

% Outputs:                                                                                                                                               
    % matrix_of_Selected_Statistics_for_all_Bursts (Matrix)
        %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        % Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
        % Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
        % Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
        %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
        %              |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                       |                                                                                                                                                                                  
        %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        %              |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                             |
        %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      


    % matrix_of_FingerPrints_for_all_Bursts (Matrix)
        %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        % Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
        % Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
        % Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
        %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
        %              |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
        %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      



    %% Section 0: Preliminaries

    %% Section 1: Collecting Essential Parameters
        % Level 1: Converting the 'Vertical_Structure_of_all_Bursts' to 'Vertical Case'
            Vertical_Structure_of_all_Bursts = Converter_to_Horizontal_or_Vertical_Vector( Vertical_Structure_of_all_Bursts, 'Vertical', 'vertical_Structure_of_a_Single_Burst' );     
        
    %% Section 2: Calculation of 'Statistic' for all 'Bursts'
        matrix_of_Selected_Statistics_for_all_Bursts = [];
        cell_of_Names_of_Covered_Fields_for_all_Bursts_in_Order = [];
        index_for_Saving_the_Burst = 1;
        for burst_Index = 1 : size ( Vertical_Structure_of_all_Bursts, 1 )
            % Level 1: Extraction of a Single Burst
                vertical_Structure_of_a_Single_Burst                         = Vertical_Structure_of_all_Bursts ( burst_Index, 1 ). a_Single_Burst;

            % Level 2: Extraction of 'Statistics' for a Single Burst                
                [ vertical_Structure_of_Selected_Statistics_for_a_Single_Burst, should_we_Omit_the_Whole_Single_Burst, horizontal_Vector_of_Lengths_of_all_subRegions_for_a_Single_Burst ] = Static_Extractor_for_a_Single_Burst (   vertical_Structure_of_a_Single_Burst,        ...
                                                                                                                                                                                                                                     vertical_Cell_of_Characteristics_Names,      ...
                                                                                                                                                                                                                                     vertical_Cell_of_Statistics_Names );
                                                                                                                                                            
                if ( should_we_Omit_the_Whole_Single_Burst == 1 ) 
                    continue;
                    
                end
                                            
                    % vertical_Structure_of_Selected_Statistics_for_a_Single_Burst (Structure):                                                                                                                                                                                                                                                              
                        %  ---------------------------------------------------------------------------------------------------------------------------------
                        %  |     | Amplitude_Element  (Field):                               Amplitude_Element                        (Vector)             |
                        %  |     | Phase_Element      (Field):                                   Amplitude                            (Vector)             |
                        %  |     | Frequency_Element  (Field):                                 Phase_Element                          (Vector)             |
                        %  |     |                                                                                                                         |
                        %  |     | Skewness_of_Amplitude_Element (Field):               Skewness_of_Amplitude_Element                 (Scalar)             |
                        %  |     | Skewness_of_Phase_Element     (Field):                 Skewness_of_Phase_Element                   (Scalar)             |
                        %  |     | Skewness_of_Frequency_Element (Field):               Skewness_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Variance_of_Amplitude_Element (Field):               Variance_of_Amplitude_Element                 (Scalar)             |
                        %  |  1  | Variance_of_Phase_Element     (Field):                 Variance_of_Phase_Element                   (Scalar)             |
                        %  |     | Variance_of_Frequency_Element (Field):               Variance_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Kurtosis_of_Amplitude_Element (Field):               Kurtosis_of_Amplitude_Element                 (Scalar)             |
                        %  |     | Kurtosis_of_Phase_Element     (Field):                 Kurtosis_of_Phase_Element                   (Scalar)             |
                        %  |     | Kurtosis_of_Frequency_Element (Field):               Kurtosis_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Mean_of_Amplitude_Element     (Field):                 Mean_of_Amplitude_Element                   (Scalar)             |
                        %  |     | Mean_of_Phase_Element         (Field):                   Mean_of_Phase_Element                     (Scalar)             |
                        %  |     | Mean_of_Frequency_Element     (Field):                 Mean_of_Frequency_Element                   (Scalar)             |                                
                        %  ---------------------------------------------------------------------------------------------------------------------------------
                        %                         .                                                   .                                  .                 |
                        %                         .                                                   .                                  .                 |
                        %                         .                                                   .                                  .                 |
                        %  ---------------------------------------------------------------------------------------------------------------------------------
                        %  |     | Amplitude_Element  (Field):                               Amplitude_Element                        (Vector)             |
                        %  |     | Phase_Element      (Field):                                   Amplitude                            (Vector)             |
                        %  |     | Frequency_Element  (Field):                                 Phase_Element                          (Vector)             |
                        %  |     |                                                                                                                         |
                        %  |     | Skewness_of_Amplitude_Element (Field):               Skewness_of_Amplitude_Element                 (Scalar)             |
                        %  |     | Skewness_of_Phase_Element     (Field):                 Skewness_of_Phase_Element                   (Scalar)             |
                        %  |     | Skewness_of_Frequency_Element (Field):               Skewness_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Variance_of_Amplitude_Element (Field):               Variance_of_Amplitude_Element                 (Scalar)             |
                        %  | 33  | Variance_of_Phase_Element     (Field):                 Variance_of_Phase_Element                   (Scalar)             |
                        %  |     | Variance_of_Frequency_Element (Field):               Variance_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Kurtosis_of_Amplitude_Element (Field):               Kurtosis_of_Amplitude_Element                 (Scalar)             |
                        %  |     | Kurtosis_of_Phase_Element     (Field):                 Kurtosis_of_Phase_Element                   (Scalar)             |
                        %  |     | Kurtosis_of_Frequency_Element (Field):               Kurtosis_of_Frequency_Element                 (Scalar)             |
                        %  |     |                                                                                                                         |
                        %  |     | Mean_of_Amplitude_Element     (Field):                 Mean_of_Amplitude_Element                   (Scalar)             |
                        %  |     | Mean_of_Phase_Element         (Field):                   Mean_of_Phase_Element                     (Scalar)             |
                        %  |     | Mean_of_Frequency_Element     (Field):                 Mean_of_Frequency_Element                   (Scalar)             |                                
                        %-----------------------------------------------------------------------------------------------------------------------------------
                         
                        
            
            % Level 3: Saving Information for Bursts
                information_of_all_Bursts ( index_for_Saving_the_Burst, 1 ).number_of_subRegions      = size ( vertical_Structure_of_a_Single_Burst, 1 ); 
                information_of_all_Bursts ( index_for_Saving_the_Burst, 1 ).lengths_of_all_subRegions = horizontal_Vector_of_Lengths_of_all_subRegions_for_a_Single_Burst;
                                        
            % Level 4: Conversion of 'vertical_Structure_of_Selected_Statistics_for_a_Single_Burst' to 'matrix_of_Selected_Statistics_for_a_Single_Burst'                         
                       % in this section, based on the strategy that the user selected, we try to form the statistics of each and all bursts
                            input_Structure.vertical_Cell_of_Characteristics_Names                       = vertical_Cell_of_Characteristics_Names;
                            input_Structure.vertical_Cell_of_Statistics_Names                            = vertical_Cell_of_Statistics_Names;
                            input_Structure.vertical_Structure_of_Selected_Statistics_for_a_Single_Burst = vertical_Structure_of_Selected_Statistics_for_a_Single_Burst;
                            
                            % 'each_Statistics_of_Characteristics_in_Seperate_Rows'
                            % or:
                            % 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row'
                            % or
                            % 'all_Statistics_of_all_Characteristics_in_Just_One_Column'
                                selected_Function_Name                               = str2func ( char ( strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix  ) );
                                [ matrix_of_Selected_Statistics_for_a_Single_Burst, vertical_Cell_of_Names_of_Covered_Fields_for_a_Single_Burst_in_Order ] = selected_Function_Name ( input_Structure );
           
            % Level 5: Accumulation of 'matrix_of_Selected_Statistics_for_a_Single_Burst'                          
                 matrix_of_Selected_Statistics_for_all_Bursts            = [ matrix_of_Selected_Statistics_for_all_Bursts,            matrix_of_Selected_Statistics_for_a_Single_Burst ];                     
                 cell_of_Names_of_Covered_Fields_for_all_Bursts_in_Order = [ cell_of_Names_of_Covered_Fields_for_all_Bursts_in_Order, vertical_Cell_of_Names_of_Covered_Fields_for_a_Single_Burst_in_Order ];

                 matrix_of_FingerPrints_for_all_Bursts ( :, index_for_Saving_the_Burst ) = FingerPrint_Generation_for_a_Single_Burst ( matrix_of_Selected_Statistics_for_a_Single_Burst, selected_Algorithm_for_Making_FingerPrint_of_a_Single_Burst );
                 index_for_Saving_the_Burst = index_for_Saving_the_Burst + 1;
                  % we used 'index_for_Saving_the_Burst' parameter instead of 'burst_Index', since:
                    % maybe sometimes 'should_we_Omit_the_Whole_Burst' was 1.
                                 
        end
        
                        % matrix_of_Selected_Statistics_for_all_Bursts (Matrix)
                            % 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row'
                            %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
                            % Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
                            % Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
                            %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            %              |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                       |                                                                                                                                                                                  
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                             |
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
                            
                            % or:                            
                            % 'each_Statistics_of_Characteristics_in_Seperate_Rows'
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              | Skewness_of_Amplitude_Element_1           ...        Skewness_of_Amplitude_Element_33 |         ...         | Skewness_of_Amplitude_Element_1           ...        Skewness_of_Amplitude_Element_33 |       
                            % Amplitude:   | Variance_of_Amplitude_Element_1           ...        Variance_of_Amplitude_Element_33 |         ...         | Variance_of_Amplitude_Element_1           ...        Variance_of_Amplitude_Element_33 |
                            %              | Kurtosis_of_Amplitude_Element_1           ...        Kurtosis_of_Amplitude_Element_33 |         ...         | Kurtosis_of_Amplitude_Element_1           ...        Kurtosis_of_Amplitude_Element_33 |
                            %              | Mean_of_Amplitude_Element_1               ...        Mean_of_Amplitude_Element_33     |         ...         | Mean_of_Amplitude_Element_1               ...        Mean_of_Amplitude_Element_33     |
                            %--------------|                                                                                       |         ...         |                                                                                       |
                            %              | Skewness_of_Phase_Element_1               ...        Skewness_of_Phase_Element_33     |         ...         | Skewness_of_Phase_Element_1               ...        Skewness_of_Phase_Element_33     |                                                                
                            % Phase:       | Variance_of_Phase_Element_1               ...        Variance_of_Phase_Element_33     |         ...         | Variance_of_Phase_Element_1               ...        Variance_of_Phase_Element_33     |        
                            %              | Kurtosis_of_Phase_Element_1               ...        Kurtosis_of_Phase_Element_33     |         ...         | Kurtosis_of_Phase_Element_1               ...        Kurtosis_of_Phase_Element_33     |       
                            %              | Mean_of_Phase_Element_1                   ...        Mean_of_Phase_Element_33         |         ...         | Mean_of_Phase_Element_1                   ...        Mean_of_Phase_Element_33         |       
                            %--------------|                                                                                       |         ...         |                                                                                       |
                            %              | Skewness_of_Frequency_Element_1           ...        Skewness_of_Frequency_Element_33 |         ...         | Skewness_of_Frequency_Element_1           ...        Skewness_of_Frequency_Element_33 |                             
                            % Frequency:   | Variance_of_Frequency_Element_1           ...        Variance_of_Frequency_Element_33 |         ...         | Variance_of_Frequency_Element_1           ...        Variance_of_Frequency_Element_33 |       
                            %              | Kurtosis_of_Frequency_Element_1           ...        Kurtosis_of_Frequency_Element_33 |         ...         | Kurtosis_of_Frequency_Element_1           ...        Kurtosis_of_Frequency_Element_33 |         
                            %              | Mean_of_Frequency_Element_1               ...        Mean_of_Frequency_Element_33     |         ...         | Mean_of_Frequency_Element_1               ...        Mean_of_Frequency_Element_33     |        
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |         subRegion_1                   |   ...    |            subRegion_33            |         ...         |         subRegion_1                   |   ...    |            subRegion_33            |                                                                                                                                                                                  
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                          Burst_1                                      |                                                                Burst_N                                      |
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            
                            
                            % or
                            % 'all_Statistics_of_all_Characteristics_in_Just_One_Column'
                            %------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                 |  Skewness_of_Amplitude_Element_1   |      ...      |                 |  Skewness_of_Amplitude_Element_1   |    
                            %              |                 |  Variance_of_Amplitude_Element_1   |      ...      |                 |  Variance_of_Amplitude_Element_1   |
                            %              |  sub-Region 1:  |  Kurtosis_of_Amplitude_Element_1   |      ...      |  sub-Region 1:  |  Kurtosis_of_Amplitude_Element_1   |
                            %              |                 |  Mean_of_Amplitude_Element_1       |      ...      |                 |  Mean_of_Amplitude_Element_1       |
                            %              |-----------------|                                    |      ...      |-----------------|                                    | 
                            % Amplitude:   |        .        |             .                      |      ...      |        .        |             .                      |                    
                            %              |        .        |             .                      |      ...      |        .        |             .                      |    
                            %              |        .        |             .                      |      ...      |        .        |             .                      | 
                            %              |-----------------|  Skewness_of_Amplitude_Element_33  |      ...      |-----------------|  Skewness_of_Amplitude_Element_33  | 
                            %              |                 |  Variance_of_Amplitude_Element_33  |      ...      |                 |  Variance_of_Amplitude_Element_33  | 
                            %              |  sub-Region 33: |  Kurtosis_of_Amplitude_Element_33  |      ...      |  sub-Region 33: |  Kurtosis_of_Amplitude_Element_33  | 
                            %              |                 |  Mean_of_Amplitude_Element_33      |      ...      |                 |  Mean_of_Amplitude_Element_33      |                 
                            %--------------|-----------------|                                    |      ...      |-----------------|                                    |              
                            %              |                 |  Skewness_of_Phase_Element_1       |      ...      |                 |  Skewness_of_Phase_Element_1       |                                                             
                            %              |  sub-Region 1:  |  Variance_of_Phase_Element_1       |      ...      |  sub-Region 1:  |  Variance_of_Phase_Element_1       |       
                            %              |                 |  Kurtosis_of_Phase_Element_1       |      ...      |                 |  Kurtosis_of_Phase_Element_1       |      
                            %              |                 |  Mean_of_Phase_Element_1           |      ...      |                 |  Mean_of_Phase_Element_1           |      
                            %              |-----------------|                                    |      ...      |-----------------|                                    |
                            %    Phase:    |        .        |             .                      |      ...      |        .        |             .                      |               
                            %              |        .        |             .                      |      ...      |        .        |             .                      | 
                            %              |        .        |             .                      |      ...      |        .        |             .                      | 
                            %              |-----------------|  Skewness_of_Phase_Element_33      |      ...      |-----------------|  Skewness_of_Phase_Element_33      | 
                            %              |                 |  Variance_of_Phase_Element_33      |      ...      |                 |  Variance_of_Phase_Element_33      | 
                            %              |  sub-Region 33: |  Kurtosis_of_Phase_Element_33      |      ...      |  sub-Region 33: |  Kurtosis_of_Phase_Element_33      | 
                            %              |                 |  Mean_of_Phase_Element_33          |      ...      |                 |  Mean_of_Phase_Element_33          |                
                            %--------------|-----------------|                                    |      ...      |-----------------|                                    |                                                   |
                            %              |                 |  Skewness_of_Frequency_Element_1   |      ...      |                 |  Skewness_of_Frequency_Element_1   |                      
                            %              |  sub-Region 1:  |  Variance_of_Frequency_Element_1   |      ...      |  sub-Region 1:  |  Variance_of_Frequency_Element_1   |
                            %              |                 |  Kurtosis_of_Frequency_Element_1   |      ...      |                 |  Kurtosis_of_Frequency_Element_1   |
                            %              |                 |  Mean_of_Frequency_Element_1       |      ...      |                 |  Mean_of_Frequency_Element_1       |
                            %              |-----------------|                                    |      ...      |-----------------|                                    | 
                            %  Frequency:  |        .        |             .                      |      ...      |        .        |             .                      |               
                            %              |        .        |             .                      |      ...      |        .        |             .                      |
                            %              |        .        |             .                      |      ...      |        .        |             .                      |
                            %              |-----------------|  Skewness_of_Frequency_Element_33  |      ...      |-----------------|  Skewness_of_Frequency_Element_33  | 
                            %              |                 |  Variance_of_Frequency_Element_33  |      ...      |                 |  Variance_of_Frequency_Element_33  | 
                            %              |  sub-Region 33: |  Kurtosis_of_Frequency_Element_33  |      ...      |  sub-Region 33: |  Kurtosis_of_Frequency_Element_33  | 
                            %              |                 |  Mean_of_Frequency_Element_33      |      ...      |                 |  Mean_of_Frequency_Element_33      |                  
                            %--------------------------------------------------------------------------------------------------------------------------------------------| 
                            %                           Burst 1                                   |      ...      |                    Burst N                           |
                            %--------------------------------------------------------------------------------------------------------------------------------------------|                             
                            
                            
                        % cell_of_Names_of_Covered_Fields_for_all_Bursts_in_Order (Matrix)
                            % 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row'
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % Amplitude:   | 'Skewness_of_Amplitude_Element_1'       Variance_of_Amplitude_Element_1        'Kurtosis_of_Amplitude_Element_1'        'Mean_of_Amplitude_Element_1'        ...        'Skewness_of_Amplitude_Element_33'       'Variance_of_Amplitude_Element_33'        'Kurtosis_of_Amplitude_Element_33'        'Mean_of_Amplitude_Element_33'        ...            'Skewness_of_Amplitude_Element_1'       'Variance_of_Amplitude_Element_1'        'Kurtosis_of_Amplitude_Element_1'        'Mean_of_Amplitude_Element_1'        ...        'Skewness_of_Amplitude_Element_33'       'Variance_of_Amplitude_Element_33'        'Kurtosis_of_Amplitude_Element_33'        'Mean_of_Amplitude_Element_33' |                   
                            % Phase:       | 'Skewness_of_Phase_Element_1'           Variance_of_Phase_Element_1            'Kurtosis_of_Phase_Element_1'            'Mean_of_Phase_Element_1'            ...        'Skewness_of_Phase_Element_33'           'Variance_of_Phase_Element_33'            'Kurtosis_of_Phase_Element_33'            'Mean_of_Phase_Element_33'            ...            'Skewness_of_Phase_Element_1'           'Variance_of_Phase_Element_1'            'Kurtosis_of_Phase_Element_1'            'Mean_of_Phase_Element_1'            ...        'Skewness_of_Phase_Element_33'           'Variance_of_Phase_Element_33'            'Kurtosis_of_Phase_Element_33'            'Mean_of_Phase_Element_33'     |                       
                            % Frequency:   | 'Skewness_of_Frequency_Element_1'       Variance_of_Frequency_Element_1        'Kurtosis_of_Frequency_Element_1'        'Mean_of_Frequency_Element_1'        ...        'Skewness_of_Frequency_Element_33'       'Variance_of_Frequency_Element_33'        'Kurtosis_of_Frequency_Element_33'        'Mean_of_Frequency_Element_33'        ...            'Skewness_of_Frequency_Element_1'       'Variance_of_Frequency_Element_1'        'Kurtosis_of_Frequency_Element_1'        'Mean_of_Frequency_Element_1'        ...        'Skewness_of_Frequency_Element_33'       'Variance_of_Frequency_Element_33'        'Kurtosis_of_Frequency_Element_33'        'Mean_of_Frequency_Element_33' |      
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                                                    subRegion_1                                                                           |   ...    |                                                                        subRegion_33                                                                             |    ...     |                                                                    subRegion_1                                                                                  |   ...    |                                                                        subRegion_33                                                                           |                                                                                                                                                                                  
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                                                                                                                                             Burst_1                                                                                                                                                                   |    ...     |                                                                                                                                                                    Burst_N                                                                                                                                                                 |
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                    
                            
                            % or:                            
                            % 'each_Statistics_of_Characteristics_in_Seperate_Rows'
                            %-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              | 'Skewness_of_Amplitude_Element_1'           ...        'Skewness_of_Amplitude_Element_33' |         ...         | 'Skewness_of_Amplitude_Element_1'           ...        'Skewness_of_Amplitude_Element_33' |       
                            % Amplitude:   | 'Variance_of_Amplitude_Element_1'           ...        'Variance_of_Amplitude_Element_33' |         ...         | 'Variance_of_Amplitude_Element_1'           ...        'Variance_of_Amplitude_Element_33' |
                            %              | 'Kurtosis_of_Amplitude_Element_1'           ...        'Kurtosis_of_Amplitude_Element_33' |         ...         | 'Kurtosis_of_Amplitude_Element_1'           ...        'Kurtosis_of_Amplitude_Element_33' |
                            %              | 'Mean_of_Amplitude_Element_1'               ...        'Mean_of_Amplitude_Element_33'     |         ...         | 'Mean_of_Amplitude_Element_1'               ...        'Mean_of_Amplitude_Element_33'     |
                            %--------------|                                                                                       |         ...         |                                                                                               |
                            %              | 'Skewness_of_Phase_Element_1'               ...        'Skewness_of_Phase_Element_33'     |         ...         | 'Skewness_of_Phase_Element_1'               ...        'Skewness_of_Phase_Element_33'     |                                                                
                            % Phase:       | 'Variance_of_Phase_Element_1'               ...        'Variance_of_Phase_Element_33'     |         ...         | 'Variance_of_Phase_Element_1'               ...        'Variance_of_Phase_Element_33'     |        
                            %              | 'Kurtosis_of_Phase_Element_1'               ...        'Kurtosis_of_Phase_Element_33'     |         ...         | 'Kurtosis_of_Phase_Element_1'               ...        'Kurtosis_of_Phase_Element_33'     |       
                            %              | 'Mean_of_Phase_Element_1'                   ...        'Mean_of_Phase_Element_33'         |         ...         | 'Mean_of_Phase_Element_1'                   ...        'Mean_of_Phase_Element_33          |       
                            %--------------|                                                                                       |         ...         |                                                                                               |
                            %              | 'Skewness_of_Frequency_Element_1'           ...        'Skewness_of_Frequency_Element_33' |         ...         | 'Skewness_of_Frequency_Element_1'           ...        'Skewness_of_Frequency_Element_33' |                             
                            % Frequency:   | 'Variance_of_Frequency_Element_1'           ...        'Variance_of_Frequency_Element_33' |         ...         | 'Variance_of_Frequency_Element_1'           ...        'Variance_of_Frequency_Element_33' |       
                            %              | 'Kurtosis_of_Frequency_Element_1'           ...        'Kurtosis_of_Frequency_Element_33' |         ...         | 'Kurtosis_of_Frequency_Element_1'           ...        'Kurtosis_of_Frequency_Element_33' |         
                            %              | 'Mean_of_Frequency_Element_1'               ...        'Mean_of_Frequency_Element_33'     |         ...         | 'Mean_of_Frequency_Element_1'               ...        'Mean_of_Frequency_Element_33'     |        
                            %-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |         subRegion_1                     |   ...    |            subRegion_33              |         ...         |         subRegion_1                     |   ...    |            subRegion_33              |                                                                                                                                                                                  
                            %-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                            Burst_1                                        |                                                                  Burst_N                                        |
                            %-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            
                            
                            % or
                            % 'all_Statistics_of_all_Characteristics_in_Just_One_Column'
                            %-------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                 |  'Skewness_of_Amplitude_Element_1'   |      ...      |                 |  'Skewness_of_Amplitude_Element_1'   |    
                            %              |                 |  'Variance_of_Amplitude_Element_1'   |      ...      |                 |  'Variance_of_Amplitude_Element_1'   |
                            %              |  sub-Region 1:  |  'Kurtosis_of_Amplitude_Element_1'   |      ...      |  sub-Region 1:  |  'Kurtosis_of_Amplitude_Element_1'   |
                            %              |                 |  'Mean_of_Amplitude_Element_1'       |      ...      |                 |  'Mean_of_Amplitude_Element_1'       |
                            %              |-----------------|                                      |      ...      |-----------------|                                      | 
                            % Amplitude:   |        .        |             .                        |      ...      |        .        |             .                        |                    
                            %              |        .        |             .                        |      ...      |        .        |             .                        |    
                            %              |        .        |             .                        |      ...      |        .        |             .                        | 
                            %              |-----------------|  'Skewness_of_Amplitude_Element_33'  |      ...      |-----------------|  'Skewness_of_Amplitude_Element_33'  | 
                            %              |                 |  'Variance_of_Amplitude_Element_33'  |      ...      |                 |  'Variance_of_Amplitude_Element_33'  | 
                            %              |  sub-Region 33: |  'Kurtosis_of_Amplitude_Element_33'  |      ...      |  sub-Region 33: |  'Kurtosis_of_Amplitude_Element_33'  | 
                            %              |                 |  'Mean_of_Amplitude_Element_33'      |      ...      |                 |  'Mean_of_Amplitude_Element_33'      |                 
                            %--------------|-----------------|                                      |      ...      |-----------------|                                      |              
                            %              |                 |  'Skewness_of_Phase_Element_1'       |      ...      |                 |  'Skewness_of_Phase_Element_1'       |                                                             
                            %              |  sub-Region 1:  |  'Variance_of_Phase_Element_1'       |      ...      |  sub-Region 1:  |  'Variance_of_Phase_Element_1'       |       
                            %              |                 |  'Kurtosis_of_Phase_Element_1'       |      ...      |                 |  'Kurtosis_of_Phase_Element_1'       |      
                            %              |                 |  'Mean_of_Phase_Element_1'           |      ...      |                 |  'Mean_of_Phase_Element_1'           |      
                            %              |-----------------|                                      |      ...      |-----------------|                                      |
                            %    Phase:    |        .        |             .                        |      ...      |        .        |             .                        |               
                            %              |        .        |             .                        |      ...      |        .        |             .                        | 
                            %              |        .        |             .                        |      ...      |        .        |             .                        | 
                            %              |-----------------|  'Skewness_of_Phase_Element_33'      |      ...      |-----------------|  'Skewness_of_Phase_Element_33'      | 
                            %              |                 |  'Variance_of_Phase_Element_33'      |      ...      |                 |  'Variance_of_Phase_Element_33'      | 
                            %              |  sub-Region 33: |  'Kurtosis_of_Phase_Element_33'      |      ...      |  sub-Region 33: |  'Kurtosis_of_Phase_Element_33'      | 
                            %              |                 |  'Mean_of_Phase_Element_33'          |      ...      |                 |  'Mean_of_Phase_Element_33'          |                
                            %--------------|-----------------|                                      |      ...      |-----------------|                                      |                                                   |
                            %              |                 |  'Skewness_of_Frequency_Element_1'   |      ...      |                 |  'Skewness_of_Frequency_Element_1'   |                      
                            %              |  sub-Region 1:  |  'Variance_of_Frequency_Element_1'   |      ...      |  sub-Region 1:  |  'Variance_of_Frequency_Element_1'   |
                            %              |                 |  'Kurtosis_of_Frequency_Element_1'   |      ...      |                 |  'Kurtosis_of_Frequency_Element_1'   |
                            %              |                 |  'Mean_of_Frequency_Element_1'       |      ...      |                 |  'Mean_of_Frequency_Element_1'       |
                            %              |-----------------|                                      |      ...      |-----------------|                                      | 
                            %  Frequency:  |        .        |             .                        |      ...      |        .        |             .                        |               
                            %              |        .        |             .                        |      ...      |        .        |             .                        |
                            %              |        .        |             .                        |      ...      |        .        |             .                        |
                            %              |-----------------|  'Skewness_of_Frequency_Element_33'  |      ...      |-----------------|  'Skewness_of_Frequency_Element_33'  | 
                            %              |                 |  'Variance_of_Frequency_Element_33'  |      ...      |                 |  'Variance_of_Frequency_Element_33'  | 
                            %              |  sub-Region 33: |  'Kurtosis_of_Frequency_Element_33'  |      ...      |  sub-Region 33: |  'Kurtosis_of_Frequency_Element_33'  | 
                            %              |                 |  'Mean_of_Frequency_Element_33'      |      ...      |                 |  'Mean_of_Frequency_Element_33'      |                  
                            %------------------------------------------------------------------------------------------------------------------------------------------------| 
                            %                           Burst 1                                     |      ...      |                    Burst N                             |
                            %------------------------------------------------------------------------------------------------------------------------------------------------|                             
                                                        
                            

%--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                          
%--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
%--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
%--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
%--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




                        % matrix_of_FingerPrints_for_all_Bursts (Matrix)
                            % 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row'
                            %              --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
                            % Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
                            % Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
                            %              -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            %              |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
                            %              ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
                                                                

                            % or:
                            
                            % 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row'
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              | selected_Function ( Skewness_of_Amplitude_Element_1           ...        Skewness_of_Amplitude_Element_33) |         ...         | selected_Function ( Skewness_of_Amplitude_Element_1           ...        Skewness_of_Amplitude_Element_33) |       
                            % Amplitude:   | selected_Function ( Variance_of_Amplitude_Element_1           ...        Variance_of_Amplitude_Element_33) |         ...         | selected_Function ( Variance_of_Amplitude_Element_1           ...        Variance_of_Amplitude_Element_33) |
                            %              | selected_Function ( Kurtosis_of_Amplitude_Element_1           ...        Kurtosis_of_Amplitude_Element_33) |         ...         | selected_Function ( Kurtosis_of_Amplitude_Element_1           ...        Kurtosis_of_Amplitude_Element_33) |
                            %              | selected_Function ( Mean_of_Amplitude_Element_1               ...        Mean_of_Amplitude_Element_33)     |         ...         | selected_Function ( Mean_of_Amplitude_Element_1               ...        Mean_of_Amplitude_Element_33)     |
                            %--------------|                                                                                                ...         |                                                                                                                                  |
                            %              | selected_Function ( Skewness_of_Phase_Element_1               ...        Skewness_of_Phase_Element_33)     |         ...         | selected_Function ( Skewness_of_Phase_Element_1               ...        Skewness_of_Phase_Element_33)     |                                                                
                            % Phase:       | selected_Function ( Variance_of_Phase_Element_1               ...        Variance_of_Phase_Element_33)     |         ...         | selected_Function ( Variance_of_Phase_Element_1               ...        Variance_of_Phase_Element_33)     |        
                            %              | selected_Function ( Kurtosis_of_Phase_Element_1               ...        Kurtosis_of_Phase_Element_33)     |         ...         | selected_Function ( Kurtosis_of_Phase_Element_1               ...        Kurtosis_of_Phase_Element_33)     |       
                            %              | selected_Function ( Mean_of_Phase_Element_1                   ...        Mean_of_Phase_Element_33)         |         ...         | selected_Function ( Mean_of_Phase_Element_1                   ...        Mean_of_Phase_Element_33)         |       
                            %--------------|                                                                                                ...         |                                                                                                                                  |
                            %              | selected_Function ( Skewness_of_Frequency_Element_1           ...        Skewness_of_Frequency_Element_33) |         ...         | selected_Function ( Skewness_of_Frequency_Element_1           ...        Skewness_of_Frequency_Element_33) |                             
                            % Frequency:   | selected_Function ( Variance_of_Frequency_Element_1           ...        Variance_of_Frequency_Element_33) |         ...         | selected_Function ( Variance_of_Frequency_Element_1           ...        Variance_of_Frequency_Element_33) |       
                            %              | selected_Function ( Kurtosis_of_Frequency_Element_1           ...        Kurtosis_of_Frequency_Element_33) |         ...         | selected_Function ( Kurtosis_of_Frequency_Element_1           ...        Kurtosis_of_Frequency_Element_33) |         
                            %              | selected_Function ( Mean_of_Frequency_Element_1               ...        Mean_of_Frequency_Element_33)     |         ...         | selected_Function ( Mean_of_Frequency_Element_1               ...        Mean_of_Frequency_Element_33)     |       
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                             subRegion_1                   |   ...    |            subRegion_33             |         ...         |                             subRegion_1                   |   ...    |             subRegion_33            |                                                                                                                                                                                  
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            %              |                                                             Burst_1                                        |                                                                Burst_N                                                           |
                            %---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            
                            
                            % or
                            % 'all_Statistics_of_all_Characteristics_in_Just_One_Column'
                            %---------------------------------------------------------------------------------------------------------
                            %              |              |                 |  selected_Function ( Skewness_of_Amplitude_Element_1)  |        
                            %              |              |                 |  selected_Function ( Variance_of_Amplitude_Element_1)  |
                            %              |              |  sub-Region 1:  |  selected_Function ( Kurtosis_of_Amplitude_Element_1)  |
                            %              |              |                 |  selected_Function ( Mean_of_Amplitude_Element_1)      |
                            %              |              |-----------------|                                                        |
                            %              | Amplitude:   |        .        |             .                                          |                
                            %              |              |        .        |             .                                          |
                            %              |              |        .        |             .                                          | 
                            %              |              |-----------------|  selected_Function ( Skewness_of_Amplitude_Element_33) | 
                            %              |              |                 |  selected_Function ( Variance_of_Amplitude_Element_33) | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Amplitude_Element_33) | 
                            %              |              |                 |  selected_Function ( Mean_of_Amplitude_Element_33)     |                 
                            %              |--------------|-----------------|                                                        | 
                            %              |              |                 |  selected_Function ( Skewness_of_Phase_Element_1)      |                                                             
                            %              |              |  sub-Region 1:  |  selected_Function ( Variance_of_Phase_Element_1)      |       
                            %              |              |                 |  selected_Function ( Kurtosis_of_Phase_Element_1)      |      
                            %              |              |                 |  selected_Function ( Mean_of_Phase_Element_1)          |      
                            %              |              |-----------------|                                                        |
                            %  Burst 1     |    Phase:    |        .        |             .                                          |               
                            %              |              |        .        |             .                                          | 
                            %              |              |        .        |             .                                          | 
                            %              |              |-----------------|  selected_Function ( Skewness_of_Phase_Element_33)     | 
                            %              |              |                 |  selected_Function ( Variance_of_Phase_Element_33)     | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Phase_Element_33)     | 
                            %              |              |                 |  selected_Function ( Mean_of_Phase_Element_33)         |                
                            %              |--------------|-----------------|                                                        |                                                   |
                            %              |              |                 |  selected_Function ( Skewness_of_Frequency_Element_1)  |                      
                            %              |              |  sub-Region 1:  |  selected_Function ( Variance_of_Frequency_Element_1)  |
                            %              |              |                 |  selected_Function ( Kurtosis_of_Frequency_Element_1)  |
                            %              |              |                 |  selected_Function ( Mean_of_Frequency_Element_1)      |
                            %              |              |-----------------|                                                        |
                            %              |  Frequency:  |        .        |             .                                          |               
                            %              |              |        .        |             .                                          |
                            %              |              |        .        |             .                                          |
                            %              |              |-----------------|  selected_Function ( Skewness_of_Frequency_Element_33) | 
                            %              |              |                 |  selected_Function ( Variance_of_Frequency_Element_33) | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Frequency_Element_33) | 
                            %              |              |                 |  selected_Function ( Mean_of_Frequency_Element_33)     |                  
                            %--------------------------------------------------------------------------------------------------------|                            
                            %              |              |                 |  selected_Function ( Skewness_of_Amplitude_Element_1)  |        
                            %              |              |                 |  selected_Function ( Variance_of_Amplitude_Element_1)  |
                            %              |              |  sub-Region 1:  |  selected_Function ( Kurtosis_of_Amplitude_Element_1)  |
                            %              |              |                 |  selected_Function ( Mean_of_Amplitude_Element_1)      |
                            %              |              |-----------------|                                                        |
                            %              | Amplitude:   |        .        |             .                                          |
                            %              |              |        .        |             .                                          |
                            %              |              |        .        |             .                                          |
                            %              |              |-----------------|  selected_Function ( Skewness_of_Amplitude_Element_33  | 
                            %              |              |                 |  selected_Function ( Variance_of_Amplitude_Element_33  | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Amplitude_Element_33  | 
                            %              |              |                 |  selected_Function ( Mean_of_Amplitude_Element_33)     |                 
                            %              |--------------|-----------------|                                                        |
                            %              |              |                 |  selected_Function ( Skewness_of_Phase_Element_1)      |                                                             
                            %              |              |  sub-Region 1:  |  selected_Function ( Variance_of_Phase_Element_1)      |       
                            %              |              |                 |  selected_Function ( Kurtosis_of_Phase_Element_1)      |      
                            %              |              |                 |  selected_Function ( Mean_of_Phase_Element_1)          |      
                            %              |              |-----------------|                                                        |
                            %  Burst N     |    Phase:    |        .        |             .                                          |               
                            %              |              |        .        |             .                                          | 
                            %              |              |        .        |             .                                          | 
                            %              |              |-----------------|  selected_Function ( Skewness_of_Phase_Element_33)     | 
                            %              |              |                 |  selected_Function ( Variance_of_Phase_Element_33)     | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Phase_Element_33)     | 
                            %              |              |                 |  selected_Function ( Mean_of_Phase_Element_33)         |                
                            %              |--------------|-----------------|                                                        |                                                   |
                            %              |              |                 |  selected_Function ( Skewness_of_Frequency_Element_1)  |                      
                            %              |              |  sub-Region 1:  |  selected_Function ( Variance_of_Frequency_Element_1)  |
                            %              |              |                 |  selected_Function ( Kurtosis_of_Frequency_Element_1)  |
                            %              |              |                 |  selected_Function ( Mean_of_Frequency_Element_1)      |
                            %              |              |-----------------|                                                        |
                            %              |  Frequency:  |        .        |             .                                          |               
                            %              |              |        .        |             .                                          |
                            %              |              |        .        |             .                                          |
                            %              |              |-----------------|  selected_Function ( Skewness_of_Frequency_Element_33) | 
                            %              |              |                 |  selected_Function ( Variance_of_Frequency_Element_33) | 
                            %              |              |  sub-Region 33: |  selected_Function ( Kurtosis_of_Frequency_Element_33 )| 
                            %              |              |                 |  selected_Function ( Mean_of_Frequency_Element_33 )    |                  
                            %---------------------------------------------------------------------------------------------------------

end

