function vertical_Structure_of_FingerPrintf_DataBank_for_all_Devices = FingerPrint_for_Multi_Devices ( varargin )
                              

% vertical_Structure_of_FingerPrintf_DataBank_for_all_Devices (Structure)
    % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % |           |                                                     |   Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
    % |           |                                                     |   Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
    % |           |                                                     |   Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
    % |           |   statistics_for_a_Single_Device (field):           |                 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    % |           |                                                     |                |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                        |                                                                                                                                                                                  
    % |           |                                                     |                 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                              |
    % | Device_1  |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
    % |           |                                                     |   Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
    % |           |                                                     |   Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
    % |           |   fingerPrint_for_a_Single_Device (field):          |   Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
    % |           |                                                     |                --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
    % -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                                                                                   
    %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                        
    %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                                                                                                   
    % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
    % |           |                                                     |   Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
    % |           |                                                     |   Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
    % |           |                                                     |   Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
    % |           |   statistics_for_a_Single_Device (field):           |                 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    % |           |                                                     |                |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                        |                                                                                                                                                                                  
    % |           |                                                     |                 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                              |
    % | Device_M  |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
    % |           |                                                     |   Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
    % |           |                                                     |   Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
    % |           |   fingerPrint_for_a_Single_Device (field):          |   Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
    % |           |                                                     |                --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
    % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        
    
        [ default_DataBank_Address, ~ ] = Folder_Address_Extractor ( 'PHD_Project_Folder', 'Resources' );
        resources_Folder_Address        = default_DataBank_Address{:};
        default_DataBank_Address        = default_DataBank_Address{:};
        default_DataBank_Address        = dir ( default_DataBank_Address );
        default_DataBank_Address        = default_DataBank_Address ( : );
        default_DataSet_Name            = default_DataBank_Address( 3, 1).name;

        inputSet = inputParser();
        inputSet.CaseSensitive = false;    
        inputSet.addParameter( 'do_You_Want_to_Make_new_DataBank', 0 );
        inputSet.addParameter( 'selected_DataBank_Methods', 'Skewness' );    
        inputSet.addParameter( 'strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix', 'each_Statistics_of_Characteristics_in_Seperate_Rows' );
        inputSet.addParameter( 'selected_DataSet_Name', default_DataSet_Name );
        inputSet.addParameter( 'vertical_Cell_of_Characteristics_Names', {'Amplitude_Element', 'Phase_Element', 'Amplitude_Element'} );
        inputSet.addParameter( 'vertical_Cell_of_Statistics_Names', {'Skewness', 'Variance', 'Mean'} );    
        inputSet.addParameter( 'vertical_Structure_of_all_Devices', [] );
        inputSet.parse( varargin{:} );

        do_You_Want_to_Make_new_DataBank                            = inputSet.Results.do_You_Want_to_Make_new_DataBank;
        selected_DataBank_Methods                                   = inputSet.Results.selected_DataBank_Methods;    
        strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix   = inputSet.Results.strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix;
        selected_DataSet_Name                                       = inputSet.Results.selected_DataSet_Name;
        vertical_Cell_of_Characteristics_Names                      = inputSet.Results.vertical_Cell_of_Characteristics_Names;
        vertical_Cell_of_Statistics_Names                           = inputSet.Results.vertical_Cell_of_Statistics_Names;        
        vertical_Structure_of_all_Devices                           = inputSet.Results.vertical_Structure_of_all_Devices;

        if ( exist ( [ resources_Folder_Address   '\' selected_DataSet_Name '\DataBank\DataBank.mat' ], 'file' ) == 0 ) || ...
                   ( do_You_Want_to_Make_new_DataBank == 1 )

                fprintf ( 'DataBank Making Started ... \n' ) 

                %% Section 1: Initial Paramater Extractions
                    % Level 1: Management of Input
                        vertical_Structure_of_all_Devices = Converter_to_Horizontal_or_Vertical_Vector ( vertical_Structure_of_all_Devices, 'Vertical', 'Multi Device Characteristic Extraction' );                       

                %% Section 2: Generation of 'DataBank'
                    DataBank_Maker (   vertical_Cell_of_Characteristics_Names,                        ...
                                       vertical_Cell_of_Statistics_Names,                                    ...
                                       selected_DataBank_Methods,  ...
                                       strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix, ...
                                       vertical_Structure_of_all_Devices,                                    ...
                                       selected_DataSet_Name, ...
                                       resources_Folder_Address );

                    vertical_Structure_of_FingerPrintf_DataBank_for_all_Devices = load ( [ resources_Folder_Address   '\' selected_DataSet_Name '\DataBank\DataBank.mat' ] );

                fprintf ( 'DataBank Making Finished! \n' )

        else
            fprintf ( 'DataBank Loading Started ... \n' ) 
            vertical_Structure_of_FingerPrintf_DataBank_for_all_Devices         = load ( [ resources_Folder_Address   '\' selected_DataSet_Name '\DataBank\DataBank.mat' ] );
            fprintf ( 'DataBank Loading Finished! \n' )

        end




    end

    %% Section 3: DataBank Making
        function DataBank_Maker (  vertical_Cell_of_Characteristics_Names,                    ...
                                   vertical_Cell_of_Statistics_Names,                         ...
                                   selected_DataBank_Methods,                                 ...
                                   strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix, ...
                                   vertical_Structure_of_all_Devices,                         ...
                                   selected_DataSet_Name,                                     ...
                                   resources_Folder_Address)

            % Level 1: Initial Paramater Extractions
                % Stage 1: Management of Input
                    vertical_Structure_of_all_Devices = Converter_to_Horizontal_or_Vertical_Vector ( vertical_Structure_of_all_Devices, 'Vertical', 'Multi Device Characteristic Extraction' );                       
                    
% % Stage 2: Seperation of Devices which should be used in formation of 'Data-Bank' based on user's preference                   
% 
% for index = 1 : size ( selected_Devices_for_Data_Making )
%     for device_Index = 1 : size ( vertical_Structure_of_all_Devices, 1 )
%         indices_of_Devices( device_Index, 1 ) = vertical_Structure_of_all_Devices ( device_Index, 1 ).device_Index;
% 
%     end
% end
    
            % Level 2: Collecting Fingerprints for Multi Devices 
                for device_Index = 1 : size ( vertical_Structure_of_all_Devices, 1 )
                    Vertical_Structure_of_a_Single_Device = vertical_Structure_of_all_Devices ( device_Index, 1 ).a_Single_Device;
                    [ matrix_of_Selected_Statistics_for_Current_Device, matrix_of_Selected_Fingerprints_for_Current_Device, cell_of_Names_of_Covered_Fields_for_current_Device, information_of_Bursts_for_Current_Device ] =  FingerPrints_for_a_Single_Device (    vertical_Cell_of_Characteristics_Names,                               ...                                          ... used here
                                                                                                                                                                                                                                                                    vertical_Cell_of_Statistics_Names,                                    ... used here
                                                                                                                                                                                                                                                                                                                                          ...
                                                                                                                                                                                                                                                                    strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix,            ... 'all_Statistics_of_the_Same_Characteristics_in_Just_One_Row' or 'each_Statistics_of_Characteristics_in_Seperate_Rows'                                                                  
                                                                                                                                                                                                                                                                    selected_DataBank_Methods,                                            ...
                                                                                                                                                                                                                                                                    Vertical_Structure_of_a_Single_Device);

                    vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).fingerPrint_for_a_Single_Device           = matrix_of_Selected_Fingerprints_for_Current_Device;
                    vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).statistics_for_a_Single_Device            = matrix_of_Selected_Statistics_for_Current_Device;
                    vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).cell_of_FieldNames_for_a_Single_Device    = cell_of_Names_of_Covered_Fields_for_current_Device;
                    vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).information_of_Bursts_for_Current_Device  = information_of_Bursts_for_Current_Device;

                        % vertical_Structure_of_FingerPrint_DataBank_for_all_Devices (Structure)
                            % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % |           |                                                     |   Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
                            % |           |                                                     |   Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
                            % |           |                                                     |   Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
                            % |           |   statistics_for_a_Single_Device (field):           |                 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            % |           |                                                     |                |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                        |                                                                                                                                                                                  
                            % |           |                                                     |                 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                              |
                            % | Device_1  |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
                            % |           |                                                     |   Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
                            % |           |                                                     |   Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
                            % |           |   fingerPrint_for_a_Single_Device (field):          |   Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
                            % |           |                                                     |                --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
                            % -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                                                                                   
                            %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                        
                            %                                     .                                                                                              .                                                                .                                                                                        .                                                                                            .                                                                                             .                                     .                                                                                                                                                               .                                                        |                                                                                                                                   
                            % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
                            % |           |                                                     |   Amplitude:   | Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33        ...            Skewness_of_Amplitude_Element_1       Variance_of_Amplitude_Element_1        Kurtosis_of_Amplitude_Element_1        Mean_of_Amplitude_Element_1        ...        Skewness_of_Amplitude_Element_33       Variance_of_Amplitude_Element_33        Kurtosis_of_Amplitude_Element_33        Mean_of_Amplitude_Element_33 |                   
                            % |           |                                                     |   Phase:       | Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33            ...            Skewness_of_Phase_Element_1           Variance_of_Phase_Element_1            Kurtosis_of_Phase_Element_1            Mean_of_Phase_Element_1            ...        Skewness_of_Phase_Element_33           Variance_of_Phase_Element_33            Kurtosis_of_Phase_Element_33            Mean_of_Phase_Element_33     |                       
                            % |           |                                                     |   Frequency:   | Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33        ...            Skewness_of_Frequency_Element_1       Variance_of_Frequency_Element_1        Kurtosis_of_Frequency_Element_1        Mean_of_Frequency_Element_1        ...        Skewness_of_Frequency_Element_33       Variance_of_Frequency_Element_33        Kurtosis_of_Frequency_Element_33        Mean_of_Frequency_Element_33 |      
                            % |           |   statistics_for_a_Single_Device (field):           |                 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            % |           |                                                     |                |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                     |    ...     |                                                                    subRegion_1                                                                     |   ...    |                                                                        subRegion_33                                                                        |                                                                                                                                                                                  
                            % |           |                                                     |                 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                                           |    ...     |                                                                                                                                                       Burst_N                                                                                                                                                              |
                            % | Device_M  |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                      
                            % |           |                                                     |   Amplitude:   | selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)        ...            selected_Function ( Skewness_of_Amplitude_Element_1, Variance_of_Amplitude_Element_1, Kurtosis_of_Amplitude_Element_1, Mean_of_Amplitude_Element_1, ..., Skewness_of_Amplitude_Element_33, Variance_of_Amplitude_Element_33, Kurtosis_of_Amplitude_Element_33, Mean_of_Amplitude_Element_33)                                                   |                  
                            % |           |                                                     |   Phase:       | selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)            ...            selected_Function ( Skewness_of_Phase_Element_1,     Variance_of_Phase_Element_1,     Kurtosis_of_Phase_Element_1,     Mean_of_Phase_Element_1,     ..., Skewness_of_Phase_Element_33,     Variance_of_Phase_Element_33,     Kurtosis_of_Phase_Element_33,     Mean_of_Phase_Element_33)                                                       |                            
                            % |           |   fingerPrint_for_a_Single_Device (field):          |   Frequency:   | selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)        ...            selected_Function ( Skewness_of_Frequency_Element_1, Variance_of_Frequency_Element_1, Kurtosis_of_Frequency_Element_1, Mean_of_Frequency_Element_1, ..., Skewness_of_Frequency_Element_33, Variance_of_Frequency_Element_33, Kurtosis_of_Frequency_Element_33, Mean_of_Frequency_Element_33)                                                   |                                                           
                            % |           |                                                     |                --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                            % |           |                                                     |                |                                                                                                                                                       Burst_1                                                                                                                                  |    ...     |                                                                                                                                                      Burst_N                                                                                                                                                                                        |
                            % --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                end                 

                address_of_Saving_DataBank       =      [ resources_Folder_Address   '\' selected_DataSet_Name '\DataBank\DataBank.mat' ];            

                save( address_of_Saving_DataBank, 'vertical_Structure_of_FingerPrint_DataBank_for_all_Devices')
                
                
    %% Section 3: Saving the 'strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix'
                  % for the time of 'formation' of 'FingerPrintPlot' 
                        number_of_Devices = size ( vertical_Structure_of_FingerPrint_DataBank_for_all_Devices, 1 );
                        
                        lengths_Matrix_for_all_Devices = [];   
                        cell_of_FieldNames_for_all_Devices = [];
                        for  device_Index = 1 : number_of_Devices                            
                            number_of_Bursts_for_Current_Device = size ( vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).information_of_Bursts_for_Current_Device ,1 );                            
                            number_of_bursts_for_all_Devices ( device_Index, 1 ) = number_of_Bursts_for_Current_Device;
                            
                            cell_of_FieldNames_for_Current_Device = vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).cell_of_FieldNames_for_a_Single_Device;                            
                            cell_of_FieldNames_for_all_Devices    = [ cell_of_FieldNames_for_all_Devices, cell_of_FieldNames_for_Current_Device ];
                            
                            for burst_Index = 1 : number_of_Bursts_for_Current_Device
                                temp = vertical_Structure_of_FingerPrint_DataBank_for_all_Devices ( device_Index, 1 ).information_of_Bursts_for_Current_Device;
                                number_of_subRegions_for_Current_Burst = temp ( burst_Index, 1 ).number_of_subRegions;
                                
                                number_of_subRegions_in_a_Single_Burst = number_of_subRegions_for_Current_Burst;
                                temp_1 = temp ( burst_Index, 1 ).lengths_of_all_subRegions;
                                for subRegion_Index = 1 : number_of_subRegions_for_Current_Burst
                                    
                                    lengths_Matrix_for_a_Single_Device ( subRegion_Index, burst_Index  ) = temp_1 ( 1, subRegion_Index );
                                    lenght_of_a_Single_subRegion = lengths_Matrix_for_a_Single_Device (1,1);
                                    
                                end
                                
                            end
                            
                            lengths_Matrix_for_all_Devices = [ lengths_Matrix_for_all_Devices, lengths_Matrix_for_a_Single_Device ];
                        
                        end

                        temp_Address = [ resources_Folder_Address   '\' selected_DataSet_Name '\DataBank' ];                                                                                    
                        address_of_Saving_FPPlot_Strategy = [ temp_Address '\Single_Burst_Strategy_for_FPPlot.txt' ];                                                                                    
                        fid = fopen(address_of_Saving_FPPlot_Strategy,'w');
                        fprintf( fid, char( strategy_of_Formation_of_a_Single_Burst_Statistics_Matrix ) );
                        fclose(fid);
                        
                        save( [ temp_Address '\cell_of_FieldNames_for_all_Devices.mat' ] ,'cell_of_FieldNames_for_all_Devices' );
                        save( [ temp_Address '\lengths_Matrix_for_all_Devices.mat' ] ,'lengths_Matrix_for_all_Devices' );
                        save( [ temp_Address '\lenght_of_a_Single_subRegion.mat' ] ,'lenght_of_a_Single_subRegion' );
                        save( [ temp_Address '\number_of_subRegions_in_a_Single_Burst.mat' ] ,'number_of_subRegions_in_a_Single_Burst' );
                        save( [ temp_Address '\number_of_bursts_for_all_Devices.mat' ] ,'number_of_bursts_for_all_Devices' );
                        save( [ temp_Address '\number_of_Devices.mat' ] ,'number_of_Devices' );
                        save( [ temp_Address '\vertical_Cell_of_Statistics_Names.mat' ] ,'vertical_Cell_of_Statistics_Names' );
                        save( [ temp_Address '\vertical_Cell_of_Characteristics_Names.mat' ] ,'vertical_Cell_of_Characteristics_Names' );
                
                
        end




